# ---------- etapa base ----------
    FROM node:20-alpine AS base
    WORKDIR /app
    # Las tres siguientes líneas permiten reproducibilidad y evitan problemas de huso horario
    ENV TZ=America/Bogota
    ENV NODE_ENV=production
    # ENV NUXT_TELEMETRY_DISABLED=1   # opcional, evita el prompt de telemetría
    
    # ---------- etapa dev ----------


    FROM base AS dev
    # 1️⃣ Dependencias (aprovecha caché si sólo cambia package*.json)
    COPY ./app/package.json ./
    RUN npm install
    # 2️⃣ Código fuente
    COPY ./app .
    EXPOSE 3000
    CMD ["npm", "run", "dev", "--", "--host"]




    
    FROM base AS builder
        
    COPY ./app/package.json ./
    RUN npm install         
    COPY . ./app
    RUN npm run build
    
    # ---------- etapa prod ----------
    FROM node:20-alpine AS prod

    ENV NODE_ENV=production
    # 1️⃣ Copio sólo lo mínimo para ejecutar el servidor Nuxt
    COPY --from=builder /app/.output ./.output
    COPY --from=builder /app/node_modules ./node_modules
    # 2️⃣ Si usas variables (por ejemplo claves API) decláralas con ENV o en docker-compose
    EXPOSE 3000
    CMD ["node", ".output/server/index.mjs"]
    